user_input = input("Enter some text: ")
user_input = user_input.replace("a","4")
user_input = user_input.replace("b","8")
user_input = user_input.replace("e","3")
user_input = user_input.replace("l","1")
user_input = user_input.replace("o","0")
user_input = user_input.replace("s","5")
user_input = user_input.replace("t","7")
print(user_input)
      
